// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYSRYnp61xIfZDmv8LGmCyoXP77pdH64',
    appId: '1:211336002267:web:your-web-app-id',
    messagingSenderId: '211336002267',
    projectId: 'zenscreen-efc9f',
    authDomain: 'zenscreen-efc9f.firebaseapp.com',
    storageBucket: 'zenscreen-efc9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYSRYnp61xIfZDmv8LGmCyoXP77pdH64',
    appId: '1:211336002267:android:8507ba098fb5a9f5622afe',
    messagingSenderId: '211336002267',
    projectId: 'zenscreen-efc9f',
    storageBucket: 'zenscreen-efc9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYSRYnp61xIfZDmv8LGmCyoXP77pdH64',
    appId: '1:211336002267:ios:your-ios-app-id',
    messagingSenderId: '211336002267',
    projectId: 'zenscreen-efc9f',
    storageBucket: 'zenscreen-efc9f.firebasestorage.app',
    iosBundleId: 'com.zenscreen.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYSRYnp61xIfZDmv8LGmCyoXP77pdH64',
    appId: '1:211336002267:ios:your-macos-app-id',
    messagingSenderId: '211336002267',
    projectId: 'zenscreen-efc9f',
    storageBucket: 'zenscreen-efc9f.firebasestorage.app',
    iosBundleId: 'com.zenscreen.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnYSRYnp61xIfZDmv8LGmCyoXP77pdH64',
    appId: '1:211336002267:web:your-windows-app-id',
    messagingSenderId: '211336002267',
    projectId: 'zenscreen-efc9f',
    authDomain: 'zenscreen-efc9f.firebaseapp.com',
    storageBucket: 'zenscreen-efc9f.firebasestorage.app',
  );
}
